CATEGORIES = [
    "Send Money",
    "Pay Bill",
    "Buy Goods",
    "Airtime",
    "Withdraw",
    "Deposit",
    "Money In",
    "Other",
]

CATEGORY_PATTERNS = {
    "Send Money": [
        "customer transfer to",
        "transfer to",
        "send money",
        "sent to",
        "customer payment to small business",
        "transfer of funds charge",
    ],
    "Pay Bill": [
        "pay bill online to",
        "pay bill charge",
        "pay bill",
        "paybill",
        "business no",
        "account no",
    ],
    "Buy Goods": [
        "merchant payment online",
        "merchant payment",
        "pay merchant charge",
        "pay merchant",
        "buy goods",
        "till no",
    ],
    "Airtime": [
        "customer bundle purchase",
        "bundle purchase",
        "recharge for customer",
        "airtime purchase",
        "airtime",
        "safaricom data",
        "safaricom offers",
        "data bundle",
    ],
    "Withdraw": [
        "customer withdrawal at agent",
        "customer withdrawal",
        "withdrawal charge",
        "withdrawal",
        "cash out",
        "atm",
    ],
    "Deposit": [
        "agent deposit",
        "cash in",
    ],
    "Money In": [
        "funds received from",
        "received from",
        "money in",
        "credit",
    ],
}
